# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0aebe5557b9812eae4d40d2a3ffe33f2ed36b50623910d43b290b4dbfc082b8206c99a236fe7c38af2308ac494466f1571d43e783b50c0ddd02e2acf1227d40d

test:
  secret_key_base: c0f1a99ba2fc1f53b0a506bb1d5ceb142931507b6c8ff6c8f6926687e15d9164a14793d9472fde1ee480e18ed1b9f8bea71bdbde9b71f525842d1b7695b5f609

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
